apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-navigator-ibm-platform-navigator-instance
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: platform-navigator
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: >-
      payload/2-services/namespace/platform-navigator/ibm-platform-navigator-instance
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-platform-navigator-ocp4
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      releaseName: ibm-platform-navigator-instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
