apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-navigator-ibm-entitlement-key
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: platform-navigator
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/platform-navigator/ibm-entitlement-key
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-platform-navigator-ocp4
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
